workflows:
  capacitor-android:
    name: Build Capacitor Android App
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      node: 18.16.0
      java: 17
      vars:
        PACKAGE_NAME: "com.example.myapp"
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          mkdir -p www
          echo "<!DOCTYPE html><html><head><title>My App</title></head><body><h1>Hello from Capacitor!</h1></body></html>" > www/index.html
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
